networks:
  default:
    name: media
    external: true

services:
  bazarr: #Subtitle grabber
    image: ghcr.io/linuxserver/bazarr
    container_name: bazarr
    environment:
      - PUID=$PUID
      - PGID=$PGID
      - TZ=$TZ
    volumes:
      - ./bazarr:/config
      - $MEDIADIR/movies:/movies
      - $MEDIADIR/tv:/tv
    ports:
      - 6767:6767
    restart: unless-stopped

  nzbget: #Usenet download agent
    image: ghcr.io/linuxserver/nzbget
    container_name: nzbget
    environment:
      - PUID=$PUID
      - PGID=$PGID
      - TZ=$TZ
    volumes:
      - ./nzbget:/config
      - ./media/usenet:/media/usenet
      - $MEDIADIR:/media
    expose:
      - 6789
    ports:
      - 6789:6789
    restart: unless-stopped

  ombi: #media requesting tool
    container_name: ombi
    image: lscr.io/linuxserver/ombi:latest
    ports:
      - 3579:3579
    environment:
      - PUID=$PUID
      - PGID=$PGID
      - TZ=$TZ
      - UMASK=002
      - ARGS
      - DEBUG=no
    volumes:
      - ./ombi:/config
    restart: unless-stopped

  radarr: #Movie search agent
    image: ghcr.io/linuxserver/radarr
    container_name: radarr
    environment:
      - PUID=$PUID
      - PGID=$PGID
      - TZ=$TZ
      - UMASK=022
    volumes:
      - ./radarr:/config
      - $MEDIADIR:/media
    ports:
      - 7878:7878
    restart: unless-stopped

  sonarr: #TV show search agent
    image: ghcr.io/linuxserver/sonarr:latest
    container_name: sonarr
    environment:
      - PUID=$PUID
      - PGID=$PGID
      - TZ=$TZ
      - UMASK=022
    volumes:
      - ./sonarr:/config
      - $MEDIADIR:/media
      - ./media/usenet:/media/usenet
    ports:
      - 8989:8989
    restart: unless-stopped

  lidarr: #Music search agent
    image: lscr.io/linuxserver/lidarr:latest
    container_name: lidarr
    environment:
      - PUID=$PUID
      - PGID=$PGID
      - TZ=$TZ
    volumes:
      - ./lidarr:/config
      - $MEDIADIR/music:/media/music #optional
      - ./media/usenet:/downloads #optional
    ports:
      - 8686:8686
    restart: unless-stopped

navidrome:
    image: deluan/navidrome:latest
    user: $PUID:$PGID # should be owner of volumes
    ports:
      - "4533:4533"
    restart: unless-stopped
    environment:
      ND_SCANSCHEDULE: 1h
      ND_LOGLEVEL: info
      ND_SESSIONTIMEOUT: 24h
      ND_BASEURL: ""
    volumes:
      - "./navidrome:/data"
      - "$MEDIADIR/music:/music:ro"

audiobookshelf:
  container_name: audiobookshelf
  image: ghcr.io/advplyr/audiobookshelf:latest
  user: $PUID:$PGID
  ports:
    - 13378:80
  volumes:
    - $MEDIADIR/audiobooks:/audiobooks
    - $MEDIADIR/podcasts:/podcasts
    - ./audiobookshelf:/config
    - ./audiobookshelf/metadata:/metadata
  restart: unless-stopped
